### ISSUE TITLE
columns expected but not found: ['user_win_rate_bucket']

### ISSUE THREAD

**Issue by Ragowit** [RyanSaxe/mtg#5]
Saw a commit mentioning DMU, so I tried it out but get this error.

```
(my_env) C:\GitHub\mtg-main\mtg\scripts>python preprocess.py --expansion DMU --game_data C:\GitHub\17lands\game_data.csv --draft_data c:\GitHub\17lands\draft_data.csv --expansion_fname c:\GitHub\17lands\DMU.pkl
Traceback (most recent call last):
  File "C:\GitHub\mtg-main\mtg\scripts\preprocess.py", line 34, in <module>
    main()
  File "C:\GitHub\mtg-main\mtg\scripts\preprocess.py", line 8, in main
    expansion = EXPANSION(bo1=FLAGS.game_data, draft=FLAGS.draft_data, ml_data=True)
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\mtg\obj\expansion.py", line 383, in __init__
    super().__init__(
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\mtg\obj\expansion.py", line 25, in __init__
    self.bo1 = self.process_data(bo1, name="bo1")
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\mtg\obj\expansion.py", line 53, in process_data
    df = load_data(file_or_df, self.cards.copy(), name=name)
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\mtg\obj\dataloading_utils.py", line 10, in load_data
    return load_bo1_data(filename, cards)
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\mtg\obj\dataloading_utils.py", line 67, in load_bo1_data
    df = pd.read_csv(
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\pandas\io\parsers\readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\pandas\io\parsers\base_parser.py", line 917, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['user_win_rate_bucket']

(my_env) C:\GitHub\mtg-main\mtg\scripts>
```

**Comment by RyanSaxe** [comment]
I can't test this right now, but can you try without game data?

When I got DMU working a few weeks ago, it was with the first dataset and hence there was only draft data (no game data).

So I haven't debugged it to see if any of those structures have changed for game data. Will try and see if I can do so over the weekend if it does have a specific issue.

(Looking at the error, a column was likely renamed since when I initially built this. Feel free to resolve that in preprocessing and open a PR if you'd like).

**Comment by Ragowit** [comment]
Hello @RyanSaxe, I pushed a PR can you maybe look at it if it's correct? And have you had the chance to look into my other issue I opened?

**Comment by Ragowit** [comment]
Hi again @RyanSaxe, sorry for bothering you but I really want to get this working in order to learn more about my drafting with your tool. :) Any chance you can look into it?

**Comment by RyanSaxe** [comment]
Hi Markus,

I'll try and look at this tomorrow. If you could ping me via DM on Twitter,
I'll be much more responsive there for working with you to resolve these
issues.

Best,
Ryan

**Comment by RyanSaxe** [comment]
Closing this as it was resolved through your PR
