### ISSUE TITLE
INVALID_ARGUMENT: required broadcastable shapes

### ISSUE THREAD

**Issue by Ragowit** [RyanSaxe/mtg#7]
I might be doing something wrong, but here's my output anyway.

```
(my_env) C:\GitHub\mtg-main\mtg\scripts>python train_drafter.py --expansion_fname c:\GitHub\17lands\DMU.pkl --model_name c:\GitHub\17lands\DMU_draft_model
2022-10-21 23:08:37.817430: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-21 23:08:39.403046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3491 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\keras\initializers\initializers_v2.py:120: UserWarning: The initializer GlorotNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
Epoch 1/1:   0%|                                                                           | 0/4947 [00:00<?, ?Batch/s]2022-10-21 23:08:48.728530: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2022-10-21 23:08:49.726358: W tensorflow/core/framework/op_kernel.cc:1768] INVALID_ARGUMENT: required broadcastable shapes
Traceback (most recent call last):
  File "C:\GitHub\mtg-main\mtg\scripts\train_drafter.py", line 173, in <module>
    main()
  File "C:\GitHub\mtg-main\mtg\scripts\train_drafter.py", line 49, in main
    trainer.train(
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\mtg\ml\trainer.py", line 127, in train
    loss, metrics = self._step(
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\mtg\ml\trainer.py", line 66, in _step
    metrics = self.model.compute_metrics(
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\mtg\ml\models.py", line 392, in compute_metrics
    tf.keras.metrics.sparse_top_k_categorical_accuracy(true, pred, 1)
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\tensorflow\python\framework\ops.py", line 7209, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} required broadcastable shapes [Op:Mul]
Epoch 1/1:   0%|                                                                           | 0/4947 [00:09<?, ?Batch/s]

(my_env) C:\GitHub\mtg-main\mtg\scripts>
```

**Comment by Ragowit** [comment]
Commented out all `@tf.function`, but the output is identical.

```
(my_env) C:\GitHub\mtg-main\mtg\scripts>python train_drafter.py --expansion_fname c:\GitHub\17lands\DMU.pkl --model_name c:\GitHub\17lands\DMU_draft_model
2022-11-02 22:53:24.980502: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-02 22:53:25.644616: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3475 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\keras\initializers\initializers_v2.py:120: UserWarning: The initializer GlorotNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
Epoch 1/1:   0%|                                                                           | 0/5540 [00:00<?, ?Batch/s]2022-11-02 22:53:29.546132: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2022-11-02 22:53:30.420130: W tensorflow/core/framework/op_kernel.cc:1768] INVALID_ARGUMENT: required broadcastable shapes
Traceback (most recent call last):
  File "C:\GitHub\mtg-main\mtg\scripts\train_drafter.py", line 173, in <module>
    main()
  File "C:\GitHub\mtg-main\mtg\scripts\train_drafter.py", line 49, in main
    trainer.train(
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\mtg\ml\trainer.py", line 127, in train
    loss, metrics = self._step(
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\mtg\ml\trainer.py", line 66, in _step
    metrics = self.model.compute_metrics(
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\mtg\ml\models.py", line 392, in compute_metrics
    tf.keras.metrics.sparse_top_k_categorical_accuracy(true, pred, 1)
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\marku\anaconda3\envs\my_env\lib\site-packages\tensorflow\python\framework\ops.py", line 7209, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:GPU:0}} required broadcastable shapes [Op:Mul]
Epoch 1/1:   0%|                                                                           | 0/5540 [00:04<?, ?Batch/s]

(my_env) C:\GitHub\mtg-main\mtg\scripts>
```

**Comment by RyanSaxe** [comment]
Closing this as this has been resolved
